model:  
  class_path: src.models.models.MyCNNToTransformerClassifier
  init_args:
    num_attention_heads: 4
    num_hidden_layers: 2
    kernel_sizes:
    - 5
    - 5
    - 2
    out_channels:
    - 8
    - 16
    - 32
    stride_sizes:
    - 5
    - 3
    - 2
    dropout_rate: 0.4
    num_labels: 2
    positional_encoding: false
    # bootstrap_val_metrics: true
    warmup_steps: 20
    learning_rate: 5e-4  # based on Merrill & Althoff, 2023 > A.1